version: '2'
services:
  zookeeper1:
    image: wurstmeister/zookeeper
    restart: always
    hostname: zookeeper1
    ports:
      - "2181:2181"
  zookeeper2:
    image: wurstmeister/zookeeper
    restart: always
    hostname: zookeeper2
    ports:
      - "2182:2181"
  zookeeper3:
    image: wurstmeister/zookeeper
    restart: always
    hostname: zookeeper3
    ports:
      - "2183:2181"
  kafka1:
    image: wurstmeister/kafka:2.12-2.3.0
    restart: always
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      JMX_PORT: 9977
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: wurstmeister/kafka:2.12-2.3.0
    restart: always
    hostname: kafka2
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      JMX_PORT: 9988
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    image: wurstmeister/kafka:2.12-2.3.0
    restart: always
    hostname: kafka3
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      JMX_PORT: 9999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#  kafka-manager:
#    image: sheepkiller/kafka-manager
#    restart: always
#    hostname: kafka-manager
#    ports:
#      - "9000:9000"
#    links:
#      - kafka1
#      - kafka2
#      - kafka3
#      - zookeeper1
#      - zookeeper2
#      - zookeeper3
#    environment:
#      KM_VERSION: 2.0.0.2
#      ZK_HOSTS: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
#      KAFKA_BROKERS: kafka1:9092,kafka2:9092,kafka3:9092
#      APPLICATION_SECRET: "letmein"