version: '2'
services:
  zookeeper1:
    image: wurstmeister/zookeeper
    hostname: zookeeper1
    ports:
      - "2181:2181"
  zookeeper2:
    image: wurstmeister/zookeeper
    hostname: zookeeper2
    ports:
      - "2182:2181"
  zookeeper3:
    image: wurstmeister/zookeeper
    hostname: zookeeper3
    ports:
      - "2183:2181"
  kafka1:
    image: wurstmeister/kafka:2.12-2.3.0
    hostname: kafka1
    ports:
      - "9091:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.4:9091
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: wurstmeister/kafka:2.12-2.3.0
    hostname: kafka2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.4:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    image: wurstmeister/kafka:2.12-2.3.0
    hostname: kafka3
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.4:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock